name: giornalino_gv_app
description: L'applicazione ufficiale del giornalino scolastico dell'I.S.I.S. P.Gobetti A.Volta
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shimmer: ^1.0.1
  http: ^0.12.0+4
  flutter_markdown:
    git:
      url: https://github.com/GioPan04/flutter_markdown.git
      ref: alignment
  url_launcher: ^5.4.1
  cupertino_icons: ^0.1.2
  intl: ^0.16.1
  share: ^0.6.3+6
  animator: ^1.0.0+5
  shared_preferences: ^0.5.6+2
  animations: ^1.0.0+5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: OpenSans-Regular
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
    - family: OpenSans-Bold
      fonts:
        - asset: fonts/OpenSans-Bold.ttf
    - family: OpenSans-SemiBold
      fonts:
        - asset: fonts/OpenSans-SemiBold.ttf
    - family: OpenSans-Light
      fonts:
        - asset: fonts/OpenSans-Light.ttf
    - family: RobotoSlab
      fonts:
        - asset: fonts/RobotoSlab.ttf
    - family: NanumMyeongjo-Regular
      fonts:
        - asset: fonts/NanumMyeongjo-Regular.ttf
    - family: NanumMyeongjo-Regular
      fonts:
        - asset: fonts/NanumMyeongjo-Bold.ttf
    - family: NanumMyeongjo-Regular
      fonts:
        - asset: fonts/NanumMyeongjo-ExtraBold.ttf