name: giornalino_gv_app
description: L'applicazione ufficiale del giornalino scolastico dell'I.S.I.S. P.Gobetti A.Volta
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+4
  flutter_markdown:
    git:
      url: https://github.com/GioPan04/flutter_markdown.git
      ref: alignment
  url_launcher: ^5.4.1
  provider: ^4.1.3
  cached_network_image: ^2.2.0+1
  animations: ^1.1.1
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: OpenSans-Regular
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
    - family: OpenSans-Bold
      fonts:
        - asset: fonts/OpenSans-Bold.ttf
    - family: OpenSans-SemiBold
      fonts:
        - asset: fonts/OpenSans-SemiBold.ttf
    - family: OpenSans-Light
      fonts:
        - asset: fonts/OpenSans-Light.ttf
    - family: RobotoSlab
      fonts:
        - asset: fonts/RobotoSlab.ttf
    - family: NanumMyeongjo-Regular
      fonts:
        - asset: fonts/NanumMyeongjo-Regular.ttf
    - family: NanumMyeongjo-Bold
      fonts:
        - asset: fonts/NanumMyeongjo-Bold.ttf
    - family: NanumMyeongjo-ExtraBold
      fonts:
        - asset: fonts/NanumMyeongjo-ExtraBold.ttf
